name: blockie_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  dio: ^4.0.6
  pointer_interceptor: ^0.9.3+3
  fluttertoast: ^8.0.9
  get: ^4.6.5
  camera: ^0.10.0+1
  json_annotation: ^4.7.0
  chopper: ^5.0.0
  logging: ^1.0.2
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  chopper_generator: ^5.0.0+1

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/app_bar/
    - images/common/
    - images/event/
    - images/settings/
