name: blockie_app
description: A Web3 sports life platform.

publish_to: 'none'

version: 1.2.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.2
  camera: ^0.10.0+1
  chinese_number: ^1.0.1
  city_pickers: ^1.1.3
  dio: ^4.0.6
  dio_log: ^2.0.4
  extended_wrap: ^0.1.2
  fluttertoast: ^8.1.1
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  get: ^4.6.5
  http_parser: ^4.0.2
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  js: ^0.6.4
  json_annotation: ^4.7.0
  package_info_plus: ^3.0.1
  pointer_interceptor: ^0.9.3+3
  statsfl: ^2.3.0
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
  json_serializable: ^6.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/activities/
    - assets/images/activity/
    - assets/images/app_bar/
    - assets/images/common/
    - assets/images/orders/
    - assets/images/order_creation/
    - assets/images/profile/
    - assets/images/project_details/
    - assets/images/projects_management/
    - assets/images/update_region/
    - assets/json_files/
    - env/
